# Generated by Django 4.1.1 on 2023-09-12 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 7, 21, 15, 672322, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
